<?php

/**
 * @file
 * Contains levchik.module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\Entity\Role;
use Drupal\user\RoleInterface;

/**
 * Implements hook_theme().
 */
function levchik_theme() {
  return [
    'guest' => [
      'template' => 'guest',
      'render element' => 'elements',
    ],
    'guest_button' => [
      'variables' => [
        'id' => NULL,
      ],
      'template' => 'guest-buttons',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function levchik_preprocess_guest(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var \Drupal\levchik\Entity\Guest $entity */
  $entity = $variables['elements']['#guest'];
  // Provide the label.
  $variables['label'] = $entity->label();
  // Provide the alias.
  $variables['url'] = $entity->toUrl()->toString();
  $variables['buttons'] = [
    '#theme' => 'guest_button',
    '#id' => $entity->id(),
  ];
  if (is_null($entity->getAvatar())) {
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#uri' => $entity->getDefaultAvatar(),
      '#alt' => t('Default Guest avatar.'),
    ];
  }
  $variables['#attached']['library'][] = 'levchik/guests-styling';
  $variables['#attached']['library'][] = 'levchik/buttons';
}
