<?php

/**
 * @file
 * Contains levchik.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\Role;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function levchik_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the levchik module.
    case 'help.page.levchik':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Guest feedback entity type.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function levchik_theme($existing, $type, $theme, $path) {
  return [
    'guest' => [
      'template' => 'guest',
      'render element' => 'elements',
    ],
    'guest_button' => [
      'variables' => [
        'id' => NULL,
      ],
      'template' => 'guest-buttons',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function levchik_preprocess_guest(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var \Drupal\levchik\Entity\Guest $entity */
  $entity = $variables['elements']['#guest'];
  //provide the label
  $variables['label'] = $entity->label();
  //provide the alias
  $variables['url'] = $entity->toUrl()->toString();
  $variables['buttons'] = [
    '#theme' => 'guest_button',
    '#id' => $entity->id(),
  ];
  if(is_null($entity->getAvatar())){
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#uri' => $entity->getDefaultAvatar(),
      '#alt' => t('Default Guest avatar.'),
    ];
  }
  $variables['#attached']['library'][] =  'levchik/guests-styling';
  $variables['#attached']['library'][] =  'levchik/buttons';
}

/**
 * Implements hook_install().
 */
function levchik_install($is_syncing) {
  $roles = Role::loadMultiple([
    RoleInterface::ANONYMOUS_ID,
    RoleInterface::AUTHENTICATED_ID
  ]);

  $issueAccessPermissions = [
    "add guest entity",
    "view guest entity"
  ];

  foreach ($issueAccessPermissions as $permission) {
    $roles[RoleInterface::AUTHENTICATED_ID]->grantPermission($permission);
    $roles[RoleInterface::ANONYMOUS_ID]->revokePermission($permission);
  }
}
